export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: {
    canDoEverything: true,
    canViewAll: true,
    canCreate: true,
    canEdit: true,
    canDelete: true,
    canExport: true,
    canImport: true,
    canAssign: true,
  },
  ADMIN: {
    canDoEverything: false,
    canViewAll: true,
    canCreate: true,
    canEdit: true,
    canDelete: false,
    canExport: false,
    canImport: true,
    canAssign: true,
  },
  COORDINADOR: {
    canDoEverything: false,
    canViewAll: true,
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canExport: false,
    canImport: true,
    canAssign: true,
  },
  ASESOR: {
    canDoEverything: false,
    canViewAll: false,
    canCreate: true,
    canEdit: true,
    canDelete: false,
    canExport: false,
    canImport: false,
    canAssign: false,
  },
};
