export const Roles = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  COORDINADOR: 'COORDINADOR',
  ADMIN: 'ADMIN',
  ASESOR: 'ASESOR',
  AUXILIAR: 'AUXILIAR',
  BODEGUERO: 'BODEGUERO',
  VENTAS: 'VENTAS',
  SUPER_PLATFORM_ADMIN: 'SUPER_PLATFORM_ADMIN',
};
